
-- BRANCH 1 CREATE STATEMENTS-----


-- CREATE TABLE for ORDER
CREATE TABLE ORDER (
    ORDER VARCHAR2(15) NOT NULL,
    "DATE" DATE NOT NULL,
    AMOUNT CHAR(5) NOT NULL,
    CSTM NUMBER(11,0),
    PRO NUMBER(11,0),
    CONSTRAINT UK_ORDER_DATE_CSTM_PRO UNIQUE (DATE, CSTM, PRO),
    CONSTRAINT FK_ORDER_CSTM FOREIGN KEY (CSTM) REFERENCES CUSTOMER(ID),
    CONSTRAINT FK_ORDER_PRO FOREIGN KEY (PRO) REFERENCES PRODUCTS(ID)
);

-- CREATE TABLE for CUSTOMERß
CREATE TABLE CUSTOMER (
    ID NUMBER(11,0) NOT NULL,
    NAME VARCHAR2(40),
    SURNAME VARCHAR2(40) NOT NULL,
    STR VARCHAR2(60),
    NO VARCHAR2(5),
    ZIP VARCHAR2(5) NOT NULL,
    PLACE VARCHAR2(50) NOT NULL,
    GEND CHAR(1),
    BDAY DATE,
    CONSTRAINT PK_CUSTOMER PRIMARY KEY (ID)
);

-- CREATE TABLE for PRODUCTS
CREATE TABLE PRODUCTS (
    ID NUMBER(11,0) NOT NULL,
    NAME VARCHAR2(50) NOT NULL,
    SORT VARCHAR2(20),
    SZ NUMBER(3,2) NOT NULL,
    PRICE NUMBER(3,2) NOT NULL,
    CONSTRAINT PK_PRODUCTS PRIMARY KEY (ID)
);



-- BRANCH 2 CREATE STATEMENTS-----


-- CREATE TABLE for PRODUCT
CREATE TABLE PRODUCT (
NUM NUMBER(12, 0) NOT NULL,
LABEL VARCHAR2(40) NOT NULL,
TYPE VARCHAR2(30) NOT NULL,
LITER NUMBER(3, 2) NOT NULL,
PRICE VARCHAR2(10) NOT NULL,
CONSTRAINT PK_PRODUCT PRIMARY KEY (NUM)
);

-- CREATE TABLE for CUSTOMER
CREATE TABLE CUSTOMER (
NUM NUMBER(12, 0) NOT NULL,
LASTNAME VARCHAR2(50) NOT NULL,
FIRSTNAME VARCHAR2(50),
PLACEID NUMBER(5, 0),
BDAY DATE,
CONSTRAINT PK_CUSTOMER PRIMARY KEY (NUM),
CONSTRAINT UK_CUSTOMER UNIQUE (LASTNAME, FIRSTNAME)
);

-- CREATE TABLE for BUYS
CREATE TABLE BUYS (
CNUMBER NUMBER(10, 0),
PNUMBER NUMBER(10, 0),
AMOUNT VARCHAR2(5) NOT NULL,
"DATE" DATE NOT NULL,
CONSTRAINT PK_BUYS PRIMARY KEY (CNUMBER, PNUMBER, AMOUNT, "DATE")
);

-- CREATE TABLE for PLACE
CREATE TABLE PLACE (
PLID NUMBER(5, 0) NOT NULL,
STR_NO VARCHAR2(70),
ZIP_PLACE VARCHAR2(100) NOT NULL,
CONSTRAINT PK_PLACE PRIMARY KEY (PLID)
);


-- BRANCH 5 CREATE STATEMENTS-----

-- CREATE TABLE for ORDERS
CREATE TABLE ORDERS (
"ORDER" VARCHAR2(30),
PRODUCT NUMBER(10, 0),
AMOUNT NUMBER(2, 0) NOT NULL
);

-- CREATE TABLE for ORDER
CREATE TABLE "ORDER" (
OID VARCHAR2(30),
"DATE" DATE NOT NULL,
CUSTOMER VARCHAR2(50) NOT NULL,
CONSTRAINT PK_ORDER PRIMARY KEY (OID)
);


-- CREATE TABLE for PLACE
CREATE TABLE PLACE (
ZIP CHAR(5) NOT NULL,
PLACE VARCHAR2(30),
CONSTRAINT PK_PLACE PRIMARY KEY (ZIP)
);

-- CREATE TABLE for CUSTOMER
CREATE TABLE CUSTOMER (
ID NUMBER(10, 0) NOT NULL,
NAME VARCHAR2(30) NOT NULL,
SURNAME VARCHAR2(30),
"STR" VARCHAR2(40) NOT NULL,
"NO" NUMBER(3, 1) NOT NULL,
ZIP CHAR(5),
GEN CHAR(1),
BDAY DATE,
CONSTRAINT FK_ZIP_PLACE FOREIGN KEY (ZIP) REFERENCES PLACE(ZIP)
);

-- CREATE TABLE for PRODUCT
CREATE TABLE PRODUCT (
ID NUMBER(10, 0) NOT NULL,
NAME VARCHAR2(30),
SORT VARCHAR2(25),
SZ NUMBER(3, 2) NOT NULL,
PRICE NUMBER(3, 2) NOT NULL,
CONSTRAINT UK_PRODUCT_ID UNIQUE (ID)
);